
export const SET_STORAGE = 'SET_STORAGE';
export const SAVE_STORAGE = 'SAVE_STORAGE';

export const FETCH_STOCK_DAY='FETCH_STOCK_DATA';
export const FETCH_STOCK_MINUTES='FETCH_STOCK_MINUTES';
export const FETCH_STOCK_KDAY='FETCH_STOCK_KDAY';
export const FETCH_STOCK_KWEEK='FETCH_STOCK_KWEEK';
export const FETCH_STOCK_KMONTH='FETCH_STOCK_KMONTH';
export const FETCH_STOCK_RANKINGS='FETCH_STOCK_RANKINGS';
